
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 304599
      POSTGRES_DB: order_service

    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always




volumes:
  postgres:
  # named volume for postgres data